version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: python:3.6-jessie
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
              # Install latest LTS node
              apt-get update
              curl -sL https://deb.nodesource.com/setup_6.x | bash -
              add-apt-repository -y ppa:ubuntugis/ppa &&
              apt update &&
              apt install -y gdal-bin python-gdal python3-gdal python3.6-dev &&
              apt-get install -y nodejs libproj-dev libgdal-dev libgeos-dev &&
              apt install -y default-jre # Required for shapely, gdal for ogr
              node --version
              gdalinfo --version
      - restore_cache:
          keys:
            - cached-directories
          paths:
            - /app/client/node_modules
            - /app/env
      - run:
          name: Install requirements
          command: |
            # Install NPM packages and build client from gulpfile
            cd /app/client
            npm install
            ./node_modules/.bin/gulp build
            cd /app
            # Install Python dependencies
            pip install virtualenv
            virtualenv env
            /app/env/bin/pip install --upgrade pip
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            /app/env/bin/pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            # JS Unit Tests
            cd /app/tests/client
            ../../client/node_modules/.bin/karma start ./karma.conf.js \
              --single-run --browsers PhantomJS --reporters junit
            # Run Python tests
            cd /app
            env/bin/nosetests ./tests/server --with-xunit \
              --xunit-file $CIRCLE_TEST_REPORTS/unitresults.xml \
              --with-coverage --cover-erase --cover-package=./server
            env/bin/coverage xml -o $CIRCLE_TEST_REPORTS/coverage.xml
      - save_cache:
          key: cached-directories
          paths:
            - /app/client/node_modules
            - /app/env
      - deploy:
          name: Deploy application
          command: |
            pip install newrelic
            newrelic-admin generate-config $NEW_RELIC_LICENSE /app/newrelic.ini
            chmod +x /app/devops/ci/circleci_deploy.sh
            /app/devops/ci/circleci_deploy.sh
